# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Microsoft Azure Internal Consumption (279f3d01-7241-445d-a4dc-dde51faf99a1)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --name rdwAKS --resource-group rdwapp-rg
      cat ~/.kube/config
      cp ~/.kube/config /home/vsts/work/1/a/test.yaml
      cat /home/vsts/work/1/a/test.yaml

- template: /test.yaml

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here     
      echo 'Hello world'
      echo $client-certificate-data

