# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- template: test.yaml

steps:
- checkout: self
  persistCredentials: true

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Microsoft Azure Internal Consumption (279f3d01-7241-445d-a4dc-dde51faf99a1)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --name rdwAKS --resource-group rdwapp-rg
      cat ~/.kube/config
      cp ~/.kube/config /home/vsts/work/1/s/test.yaml
      cat /home/vsts/work/1/s/test.yaml
      echo $(client-certificate-data)
      git config --global user.email "ruandanwei126@gmail.com"
      git config --global user.name "Suda"
      git status
      git add /home/vsts/work/1/s/test.yaml
      git remote add origin git@github.com:wyt1206/terraform-azurerm-aks.git
      git commit -m "add test1"
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin HEAD:main

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here     
      echo 'Hello world'
      echo $(client-certificate-data)